routes/web.php
<?php

use App\Http\Controllers\ClubFormController;
use App\Http\Controllers\NewsController;
use App\Http\Controllers\TermineController;
use App\Http\Controllers\VereineController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::get('/impressum', function () {
    return view('impressum.impressum');
});

Route::get('/datenschutz', function () {
    return view('datenschutz.datenschutz');
});

Route::get('/dashboard', function () {
    return view('dashboard');
})->middleware(['auth', 'verified'])->name('dashboard');

Route::resource('news', NewsController::class)
    ->middleware(['auth', 'verified']);

Route::resource('termine', TermineController::class)
    ->middleware('auth', 'verified');

Route::resource('vereine', VereineController::class)
    ->middleware('auth', 'verified');

Route::resource('foerderverein', ClubFormController::class);

require __DIR__.'/auth.php';

app/Models/Datenschutz.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Datenschutz extends Model
{
    protected $fillable = [
        'title',
        'content',
    ];
}

app/Http/Controllers/API/DatenschutzController.php
<?php

namespace App\Http\Controllers\API;

use App\Models\Appsite;

class DatenschutzController
{
    public function index()
    {
        $datenschutz = Appsite::where('content_id', 'datenschutz')->get();
        $datenschutz->toArray();

        return response()->json([
            'data' => $datenschutz,
        ]);
    }
}

app/Http/Controllers/DatenschutzController.php
<?php

namespace App\Http\Controllers;

use App\Models\Datenschutz;
use Illuminate\Http\Request;

class DatenschutzController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('datenschutz.datenschutz');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('datenschutz.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $datenschutz = new Datenschutz;
        $datenschutz->title = $request->input('title');
        $datenschutz->content = $request->input('content');

        return redirect()->route('datenschutz.index')->with('success', 'Datenschutz has been create successfully');

    }

    /**
     * Display the specified resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function show(Datenschutz $datenschutz)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function edit(Datenschutz $datenschutz)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Datenschutz $datenschutz)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @return \Illuminate\Http\Response
     */
    public function destroy(Datenschutz $datenschutz)
    {
        //
    }
}

app/View/Components/AppLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;

class AppLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     *
     * @return \Illuminate\View\View
     */
    public function render()
    {
        return view('layouts.app');
    }
}

resources/views/datenschutz/create.blade.php
<x-app-layout>
    <div class="content-center md:w-4/6 mx-auto my-3">
        <form action="{{route('datenschutz.store')}}" method="POST" enctype="multipart/form-data">
            @csrf
            <div class="shadow sm:overflow-hidden sm:rounded-md">
                <div class="space-y-6 bg-white px-4 py-5 sm:p-6">
                    <div class="grid grid-cols-3 gap-6">
                        <div class="col-span-3 sm:col-span-2">
                            <label for="title" class="block text-sm font-medium text-gray-700">Titel</label>
                            <div class="mt-1 flex rounded-md shadow-sm">
                                <input type="text" name="title" id="title"
                                       class="block w-full flex-1 rounded-md border-gray-300 focus:border-indigo-500 focus:ring-indigo-500 sm:text-sm"
                                       placeholder="Titel">
                            </div>
                        </div>
                    </div>
                    <div>
                        <label for="content" class="block text-sm font-medium text-gray-700">Inhalt</label>
                        <div class="mt-1">
                            <textarea id="content" name="content" rows="3"
                                      class="mt-1 block w-full rounded-md border-gray-300 shadow-sm focus:border-indigo-500 focus:ring-indigo-500 sm:text-sm"
                                      placeholder="Inhalt..."></textarea>
                        </div>
                        <p class="mt-2 text-sm text-gray-500">Textinhalt/Bericht</p>
                    </div>
                </div>
                <div class="bg-gray-50 px-4 py-3 text-right sm:px-6">
                    <button type="submit"
                            class="inline-flex justify-center rounded-md border border-transparent bg-indigo-600 py-2 px-4 text-sm font-medium text-white shadow-sm hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-indigo-500 focus:ring-offset-2">
                        Speichern
                    </button>
                </div>
            </div>
        </form>
    </div>
</x-app-layout>

resources/views/datenschutz/index.blade.php
<x-app-layout>
    <div class="content-center m-3">
        <div class="shadow sm:overflow-hidden sm:rounded-md">
            <div class="space-y-6 bg-white px-4 py-5 sm:p-6 container mx-auto">
                <div class="text-center">
                    <h1 class="text-2xl">Datenschutz</h1>
                </div>

                @if ($message = Session::get('success'))
                    <div class="alert alert-success">
                        <p>{{ $message }}</p>
                    </div>
                @endif

                @foreach($datenschutz as $item)
                    <div class="p-6 max-w-sm mx-auto bg-white rounded-xl shadow-lg flex items-center space-x-4">
                        <div>
                            <div class="text-xl font-bold text-black">{{ $item->title }}</div>
                            <hr/>
                            <p class="text-slate-500 text-xs pt-2">{{ $item->created_at->format('d.m.Y') }} <span class="bg-slate-500 rounded text-neutral-50 px-1">{{ $item->verein }}</span></p>
                            <p class="pt-1">{{ Str::limit($item->content, 40) }}</p>
                            <hr/>
                            <form action="{{ route('news.destroy',$item->id) }}" method="Post">
                                <a class="text-sky-500" href="{{ route('news.edit',$item->id) }}">Edit</a>
                                @csrf
                                @method('DELETE')
                                <button type="submit" class="text-red-500">Delete</button>
                            </form>
                        </div>
                    </div>
                @endforeach

                <div class="flex justify-center">
                    <a href="{{ route('datenschutz.create') }}"> <button class="rounded-lg p-2 text-white font-semibold bg-sky-500 hover:bg-sky-600">Neuer Eintrag</button></a>

                </div>
            </div>
        </div>
    </div>
</x-app-layout>