routes/web.php
<?php

use App\Http\Controllers\ClubFormController;
use App\Http\Controllers\NewsController;
use App\Http\Controllers\TermineController;
use App\Http\Controllers\VereineController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::get('/impressum', function () {
    return view('impressum.impressum');
});

Route::get('/datenschutz', function () {
    return view('datenschutz.datenschutz');
});

Route::get('/dashboard', function () {
    return view('dashboard');
})->middleware(['auth', 'verified'])->name('dashboard');

Route::resource('news', NewsController::class)
    ->middleware(['auth', 'verified']);

Route::resource('termine', TermineController::class)
    ->middleware('auth', 'verified');

Route::resource('vereine', VereineController::class)
    ->middleware('auth', 'verified');

Route::resource('foerderverein', ClubFormController::class);

require __DIR__.'/auth.php';

app/Models/News.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class News extends Model
{
    protected $fillable = [
        'user_id',
        'title',
        'message',
        'image',
        'verein',
    ];

    public function user()
    {
        return $this->belongsTo('User');
    }
}

app/Http/Controllers/API/NewsController.php
<?php

namespace App\Http\Controllers\API;

use App\Models\News;
use App\Query\NewsQueryFactory;
use Illuminate\Http\JsonResponse;

class NewsController extends ApiController
{
    public function index(): JsonResponse
    {
        $news = NewsQueryFactory::getNewsQuery()->paginate();

        return response()->json([
            'data' => $news,
        ]);
    }

    public function show(News $news): JsonResponse
    {
        return response()->json([
            'data' => $news,
        ]);
    }
}

app/Http/Controllers/NewsController.php
<?php

namespace App\Http\Controllers;

use App\Http\Services\ExpoPushNotification;
use App\Models\Device;
use App\Models\News;
use App\Models\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;

class NewsController extends Controller
{
    public function __construct(private ExpoPushNotification $notification) {}

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $news = News::orderBy('created_at', 'desc')->paginate(10);

        return view('news.index', [
            'news' => $news,
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('news.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $devices = Device::all()->pluck('token')->toArray();

        //        $news = new News();
        //        $news->user_id = Auth::id();
        //        $news->title = $request->input('title');
        //        $news->message = $request->input('description');
        //        $fileName = $request->file('file');
        //        $pic = md5(uniqid()) . '.' . $fileName->guessClientExtension();
        //        $request->file->move(public_path('images'), $pic);
        //        $news->image = $pic;
        //        $news->verein = $request->input('verein');
        //        $news->save();

        $data = [
            'deepLink' => [
                'route' => 'NewsDetails',
                'params' => [
                    'id' => '1',
                ],
            ],
        ];
        foreach ($devices as $device) {
            $this->notification->sendPushNotification($device, $request->input('title'), $request->input('description'), $data);

        }

        return redirect()->route('news.index')->with('success', 'News has been create successfully');
    }

    /**
     * Display the specified resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function show(News $news)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function edit(News $news)
    {
        return view('news.edit', [
            'news' => $news,
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, News $news)
    {
        $request->validate([
            'title' => 'required',
            'description' => 'required',
            'verein' => 'required',
        ]);
        if ($request->file('file')) {
            $fileName = $request->file('file')->getClientOriginalName();
            $request->file->move(public_path('images'), $fileName);
            $news->image = $fileName;
        }

        $news->title = $request->title;
        $news->message = $request->description;
        $news->verein = $request->verein;
        $news->user_id = Auth::id();
        $news->save();

        return redirect()->route('news.index')->with('success', 'News has been update successfully');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @return \Illuminate\Http\Response
     */
    public function destroy(News $news)
    {
        $news->delete();

        return redirect()->route('news.index')->with('success', 'News has been deleted successfully');
    }
}

app/View/Components/AppLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;

class AppLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     *
     * @return \Illuminate\View\View
     */
    public function render()
    {
        return view('layouts.app');
    }
}

resources/views/news/create.blade.php
<x-app-layout>
    <div class="content-center md:w-4/6 mx-auto my-3">
        <form action="{{route('news.store')}}" method="POST" enctype="multipart/form-data">
            @csrf
            <div class="shadow sm:overflow-hidden sm:rounded-md">
                <div class="space-y-6 bg-white px-4 py-5 sm:p-6">
                    <div class="grid grid-cols-3 gap-6">
                        <div class="col-span-3 sm:col-span-2">
                            <label for="title" class="block text-sm font-medium text-gray-700">Titel</label>
                            <div class="mt-1 flex rounded-md shadow-sm">
                                <input type="text" name="title" id="title"
                                       class="block w-full flex-1 rounded-md border-gray-300 focus:border-indigo-500 focus:ring-indigo-500 sm:text-sm"
                                       placeholder="Titel">
                            </div>
                        </div>
                    </div>
                    <div>
                        <label for="description" class="block text-sm font-medium text-gray-700">Inhalt</label>
                        <div class="mt-1">
                            <textarea id="message" name="description" rows="3"
                                      class="mt-1 block w-full rounded-md border-gray-300 shadow-sm focus:border-indigo-500 focus:ring-indigo-500 sm:text-sm"
                                      placeholder="Inhalt..."></textarea>
                        </div>
                        <p class="mt-2 text-sm text-gray-500">Textinhalt/Bericht</p>
                    </div>
                    <div>
                        <label class="block text-sm font-medium text-gray-700">Titelbild</label>
                        <div
                            class="mt-1 flex justify-center rounded-md border-2 border-dashed border-gray-300 px-6 pt-5 pb-6">
                            <div class="space-y-1 text-center">
                                <svg class="mx-auto h-12 w-12 text-gray-400" stroke="currentColor" fill="none"
                                     viewBox="0 0 48 48" aria-hidden="true">
                                    <path
                                        d="M28 8H12a4 4 0 00-4 4v20m32-12v8m0 0v8a4 4 0 01-4 4H12a4 4 0 01-4-4v-4m32-4l-3.172-3.172a4 4 0 00-5.656 0L28 28M8 32l9.172-9.172a4 4 0 015.656 0L28 28m0 0l4 4m4-24h8m-4-4v8m-12 4h.02"
                                        stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/>
                                </svg>
                                <img id="output"/>
                                <div class="flex text-sm text-gray-600">
                                    <label for="file-upload"
                                           class="relative cursor-pointer rounded-md bg-white font-medium text-indigo-600 focus-within:outline-none focus-within:ring-2 focus-within:ring-indigo-500 focus-within:ring-offset-2 hover:text-indigo-500">
                                        <span>Lade ein Bild hoch</span>
                                        <input id="file-upload" name="file" type="file" class="sr-only" onchange="loadFile(event)">
                                    </label>
                                </div>
                                <p class="text-xs text-gray-500">PNG, JPG, GIF bis maximal 10MB</p>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="bg-gray-50 px-4 py-3 text-right sm:px-6">
                    <button type="submit"
                            class="rounded-lg p-2 text-white font-semibold bg-sky-500 hover:bg-sky-600">
                        Speichern
                    </button>
                </div>
            </div>
        </form>
    </div>
    <script>
        var loadFile = function(event) {
            var output = document.getElementById('output');
            output.src = URL.createObjectURL(event.target.files[0]);
            output.onload = function() {
                URL.revokeObjectURL(output.src) // free memory
            }
        };
    </script>
</x-app-layout>

resources/views/news/edit.blade.php
<x-app-layout>
    <div class="content-center md:w-4/6 mx-auto my-3">
        <form action="{{route('news.update', $news->id)}}" method="POST" enctype="multipart/form-data">
            @csrf
            @method('PUT')
            <div class="shadow sm:overflow-hidden sm:rounded-md">
                <div class="space-y-6 bg-white px-4 py-5 sm:p-6">
                    <div class="grid grid-cols-3 gap-6">
                        <div class="col-span-3 sm:col-span-2">
                            <label for="title" class="block text-sm font-medium text-gray-700">Titel</label>
                            <div class="mt-1 flex rounded-md shadow-sm">
                                <input type="text" name="title" id="title"
                                       class="block w-full flex-1 rounded-md border-gray-300 focus:border-indigo-500 focus:ring-indigo-500 sm:text-sm"
                                       value="{{$news->title}}">
                            </div>
                        </div>
                    </div>
                    <div class="grid grid-cols-3 gap-6">
                        <div class="col-span-3 sm:col-span-2">
                            <label for="verein" class="block text-sm font-medium text-gray-700">Aktuelles von</label>
                            <div class="mb-3 xl:w-96">
                                <select name="verein" id="verein" class="form-select appearance-none
      block
      w-full
      px-3
      py-1.5
      text-base
      font-normal
      text-gray-700
      bg-white bg-clip-padding bg-no-repeat
      border border-solid border-gray-300
      rounded
      transition
      ease-in-out
      m-0
      focus:text-gray-700 focus:bg-white focus:border-blue-600 focus:outline-none" aria-label="Default select example">
                                    @if($news->verein)
                                        <option value="{{$news->verein}}" selected>{{ $news->verein }}</option>
                                    @else
                                        <option selected>Bitte angeben</option>
                                    @endif
                                    <option value="Allgemein">Allgemein</option>
                                    <option value="DJK Tinnen">DJK Tinnen</option>
                                    <option value="St. Bernadus">St. Bernadus</option>
                                    <option value="ETWAH">ETWAH</option>
                                    <option value="Tinner Jäger">Tinner Jäger</option>
                                    <option value="Jugend Blasorchester">Jugend Blasorchester</option>
                                    <option value="Oltimer Club">Oldtimer Club</option>
                                    <option value="Motorrad Club">Motorrad Club</option>
                                    <option value="Imker Verein">Imker Verein</option>
                                    <option value="KLJB Tinnen">KLJB Tinnen</option>
                                    <option value="Michael Schule">Michael Schule</option>
                                </select>
                            </div>
                        </div>
                    </div>
                    <div>
                        <label for="description" class="block text-sm font-medium text-gray-700">Inhalt</label>
                        <div class="mt-1">
                            <textarea id="message" name="description" rows="3"
                                      class="mt-1 block w-full rounded-md border-gray-300 shadow-sm focus:border-indigo-500 focus:ring-indigo-500 sm:text-sm"
                                      placeholder="Inhalt...">{{ $news->message }}</textarea>
                        </div>
                        <p class="mt-2 text-sm text-gray-500">Textinhalt/Bericht</p>
                    </div>
                    <div>
                        <label class="block text-sm font-medium text-gray-700">Titelbild</label>
                        <div
                            class="mt-1 flex justify-center rounded-md border-2 border-dashed border-gray-300 px-6 pt-5 pb-6">
                            <div class="space-y-1 text-center">
                                <svg class="mx-auto h-12 w-12 text-gray-400" stroke="currentColor" fill="none"
                                     viewBox="0 0 48 48" aria-hidden="true">
                                    <path
                                        d="M28 8H12a4 4 0 00-4 4v20m32-12v8m0 0v8a4 4 0 01-4 4H12a4 4 0 01-4-4v-4m32-4l-3.172-3.172a4 4 0 00-5.656 0L28 28M8 32l9.172-9.172a4 4 0 015.656 0L28 28m0 0l4 4m4-24h8m-4-4v8m-12 4h.02"
                                        stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/>
                                </svg>
                                <img id="output"/>
                                <div class="flex text-sm text-gray-600">
                                    <label for="file-upload"
                                           class="relative cursor-pointer rounded-md bg-white font-medium text-indigo-600 focus-within:outline-none focus-within:ring-2 focus-within:ring-indigo-500 focus-within:ring-offset-2 hover:text-indigo-500">
                                        <span>Lade ein Bild hoch</span>
                                        <input id="file-upload" name="file" type="file" class="sr-only" onchange="loadFile(event)">
                                    </label>
                                </div>
                                <p class="text-xs text-gray-500">PNG, JPG, GIF bis maximal 10MB</p>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="bg-gray-50 px-4 py-3 text-right sm:px-6">
                    <button type="submit"
                            class="rounded-lg p-2 text-white font-semibold bg-sky-500 hover:bg-sky-600">
                        Speichern
                    </button>
                </div>
            </div>
        </form>
    </div>
    <script>
        var loadFile = function(event) {
            var output = document.getElementById('output');
            output.src = URL.createObjectURL(event.target.files[0]);
            output.onload = function() {
                URL.revokeObjectURL(output.src) // free memory
            }
        };
    </script>
</x-app-layout>

resources/views/news/index.blade.php
<x-app-layout>
    <div class="content-center m-3">
        <div class="shadow sm:overflow-hidden sm:rounded-md">
            <div class="space-y-6 bg-white px-4 py-5 sm:p-6 container mx-auto">
                <div class="text-center">
                    <h1 class="text-2xl font-bold underline">Aktuell</h1>
                </div>

                @if ($message = Session::get('success'))
                    <div class="flex justify-center space-x-2">
                        <div
                            class="pointer-events-auto mx-auto mb-4 hidden w-96 max-w-full rounded-lg bg-success-100 bg-clip-padding text-sm text-success-700 shadow-lg shadow-black/5 data-[te-toast-show]:block data-[te-toast-hide]:hidden"
                            id="static-example"
                            role="alert"
                            aria-live="assertive"
                            aria-atomic="true"
                            data-te-autohide="true"
                            data-te-toast-init
                            data-te-toast-show>
                            <div
                                class="flex items-center justify-between rounded-t-lg border-b-2 border-success/20 bg-success-100 bg-clip-padding px-4 pt-2.5 pb-2">
                                <p class="flex items-center font-bold text-success-700">
                                    Aktuelles
                                </p>
                                <div class="flex items-center">
                                    <button
                                        type="button"
                                        class="ml-2 box-content rounded-none border-none opacity-80 hover:no-underline hover:opacity-75 focus:opacity-100 focus:shadow-none focus:outline-none"
                                        data-te-toast-dismiss
                                        aria-label="Close">
                                      <span
                                          class="w-[1em] focus:opacity-100 disabled:pointer-events-none disabled:select-none disabled:opacity-25 [&.disabled]:pointer-events-none [&.disabled]:select-none [&.disabled]:opacity-25">
                                        <svg
                                            xmlns="http://www.w3.org/2000/svg"
                                            fill="none"
                                            viewBox="0 0 24 24"
                                            stroke-width="1.5"
                                            stroke="currentColor"
                                            class="h-6 w-6">
                                          <path
                                              stroke-linecap="round"
                                              stroke-linejoin="round"
                                              d="M6 18L18 6M6 6l12 12"/>
                                        </svg>
                                      </span>
                                    </button>
                                </div>
                            </div>
                            <div
                                class="break-words rounded-b-lg bg-success-100 py-4 px-4 text-success-700">
                                {{ $message }}
                            </div>
                        </div>
                    </div>
                @endif
                <div class="flex justify-center">
                    <a href="{{ route('news.create') }}">  <button
                            class="ml-1 flex justify-start items-center inline-block rounded bg-sky-500 px-6 pt-2.5 pb-2 text-xs font-medium uppercase leading-normal text-white shadow-[0_4px_9px_-4px_#3b71ca] transition duration-150 ease-in-out hover:bg-primary-600 hover:shadow-[0_8px_9px_-4px_rgba(59,113,202,0.3),0_4px_18px_0_rgba(59,113,202,0.2)] focus:bg-primary-600 focus:shadow-[0_8px_9px_-4px_rgba(59,113,202,0.3),0_4px_18px_0_rgba(59,113,202,0.2)] focus:outline-none focus:ring-0 active:bg-primary-700 active:shadow-[0_8px_9px_-4px_rgba(59,113,202,0.3),0_4px_18px_0_rgba(59,113,202,0.2)]">
                            <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5"
                                 stroke="currentColor" class="w-6 h-6">
                                <path stroke-linecap="round" stroke-linejoin="round" d="M12 4.5v15m7.5-7.5h-15"/>
                            </svg>
                            <span class="text-base ml-3">Push Nachricht</span>
                        </button>
                    </a>
                </div>

            </div>
        </div>
    </div>
</x-app-layout>